using DBService.Base;

namespace DBService.Level25Repository.L2L25_CoilPDO
{
    public class L2L25_CoilPDO : BaseRepositoryModel
    {
		public string Message_Length { get; set; }
		public string Message_Id { get; set; }
		public string Date { get; set; }
		public string Time { get; set; }
		public string ORDER_NO { get; set; }
		public string PLAN_NO { get; set; }
		public string OUT_MAT_NO { get; set; }
		public string IN_MAT_NO { get; set; }
		public string START_PROD_TIME { get; set; }
		public string END_PROD_TIME { get; set; }
		public string PROD_SHIFT_NO { get; set; }
		public string PROD_SHIFT_GROUP { get; set; }
		public string OUT_MAT_ACT_OUTER_DIA { get; set; }
		public string OUT_MAT_ACT_INNER_DIA { get; set; }
		public string OUT_MAT_ACT_WT { get; set; }
		public string OUT_MAT_GROSS_WT { get; set; }
		public string OUT_MAT_ACT_THICK { get; set; }
		public string OUT_MAT_ACT_WIDTH { get; set; }
		public string OUT_MAT_ACT_LEN { get; set; }
		public string PAPER_CODE { get; set; }
		public string PAPER_REQ_CODE { get; set; }
		public string HEAD_PAPER_LENGTH { get; set; }
		public string HEAD_PAPER_WIDTH { get; set; }
		public string TAIL_PAPER_LENGTH { get; set; }
		public string TAIL_PAPER_WIDTH { get; set; }
		public string SLEEVE_DIAMTER { get; set; }
		public string SLEEVE_TYPE_CODE { get; set; }
		public string HEAD_HOLE_POSITION { get; set; }
		public string HEAD_LEADER_LENGTH { get; set; }
		public string HEAD_LEADER_WIDTH { get; set; }
		public string HEAD_LEADER_THICK { get; set; }
		public string TAIL_HOLE_POSITION { get; set; }
		public string TAIL_LEADER_LENGTH { get; set; }
		public string TAIL_LEADER_WIDTH { get; set; }
		public string TAIL_LEADER_THICK { get; set; }
		public string SCRAP_LEN_HEAD { get; set; }
		public string SCRAP_LEN_TAIL { get; set; }
		public string HEAD_LEADER_ST_NO { get; set; }
		public string TAIL_LEADER_ST_NO { get; set; }
		public string DEFECT_CODE_1 { get; set; }
		public string DEFECT_FROM_1 { get; set; }
		public string DEFECT_SURF_1 { get; set; }
		public string DEFECT_POSITION_WIDTH_1 { get; set; }
		public string DEFECT_LEN_START_1 { get; set; }
		public string DEFECT_LEN_END_1 { get; set; }
		public string DEFECT_CLASS_1 { get; set; }
		public string DEFECT_PERCENT_1 { get; set; }
		public string DEFECT_QUALITY_GRADE_1 { get; set; }
		public string DEFECT_CODE_2 { get; set; }
		public string DEFECT_FROM_2 { get; set; }
		public string DEFECT_SURF_2 { get; set; }
		public string DEFECT_POSITION_WIDTH_2 { get; set; }
		public string DEFECT_LEN_START_2 { get; set; }
		public string DEFECT_LEN_END_2 { get; set; }
		public string DEFECT_CLASS_2 { get; set; }
		public string DEFECT_PERCENT_2 { get; set; }
		public string DEFECT_QUALITY_GRADE_2 { get; set; }
		public string DEFECT_CODE_3 { get; set; }
		public string DEFECT_FROM_3 { get; set; }
		public string DEFECT_SURF_3 { get; set; }
		public string DEFECT_POSITION_WIDTH_3 { get; set; }
		public string DEFECT_LEN_START_3 { get; set; }
		public string DEFECT_LEN_END_3 { get; set; }
		public string DEFECT_CLASS_3 { get; set; }
		public string DEFECT_PERCENT_3 { get; set; }
		public string DEFECT_QUALITY_GRADE_3 { get; set; }
		public string DEFECT_CODE_4 { get; set; }
		public string DEFECT_FROM_4 { get; set; }
		public string DEFECT_SURF_4 { get; set; }
		public string DEFECT_POSITION_WIDTH_4 { get; set; }
		public string DEFECT_LEN_START_4 { get; set; }
		public string DEFECT_LEN_END_4 { get; set; }
		public string DEFECT_CLASS_4 { get; set; }
		public string DEFECT_PERCENT_4 { get; set; }
		public string DEFECT_QUALITY_GRADE_4 { get; set; }
		public string DEFECT_CODE_5 { get; set; }
		public string DEFECT_FROM_5 { get; set; }
		public string DEFECT_SURF_5 { get; set; }
		public string DEFECT_POSITION_WIDTH_5 { get; set; }
		public string DEFECT_LEN_START_5 { get; set; }
		public string DEFECT_LEN_END_5 { get; set; }
		public string DEFECT_CLASS_5 { get; set; }
		public string DEFECT_PERCENT_5 { get; set; }
		public string DEFECT_QUALITY_GRADE_5 { get; set; }
		public string DEFECT_CODE_6 { get; set; }
		public string DEFECT_FROM_6 { get; set; }
		public string DEFECT_SURF_6 { get; set; }
		public string DEFECT_POSITION_WIDTH_6 { get; set; }
		public string DEFECT_LEN_START_6 { get; set; }
		public string DEFECT_LEN_END_6 { get; set; }
		public string DEFECT_CLASS_6 { get; set; }
		public string DEFECT_PERCENT_6 { get; set; }
		public string DEFECT_QUALITY_GRADE_6 { get; set; }
		public string DEFECT_CODE_7 { get; set; }
		public string DEFECT_FROM_7 { get; set; }
		public string DEFECT_SURF_7 { get; set; }
		public string DEFECT_POSITION_WIDTH_7 { get; set; }
		public string DEFECT_LEN_START_7 { get; set; }
		public string DEFECT_LEN_END_7 { get; set; }
		public string DEFECT_CLASS_7 { get; set; }
		public string DEFECT_PERCENT_7 { get; set; }
		public string DEFECT_QUALITY_GRADE_7 { get; set; }
		public string DEFECT_CODE_8 { get; set; }
		public string DEFECT_FROM_8 { get; set; }
		public string DEFECT_SURF_8 { get; set; }
		public string DEFECT_POSITION_WIDTH_8 { get; set; }
		public string DEFECT_LEN_START_8 { get; set; }
		public string DEFECT_LEN_END_8 { get; set; }
		public string DEFECT_CLASS_8 { get; set; }
		public string DEFECT_PERCENT_8 { get; set; }
		public string DEFECT_QUALITY_GRADE_8 { get; set; }
		public string DEFECT_CODE_9 { get; set; }
		public string DEFECT_FROM_9 { get; set; }
		public string DEFECT_SURF_9 { get; set; }
		public string DEFECT_POSITION_WIDTH_9 { get; set; }
		public string DEFECT_LEN_START_9 { get; set; }
		public string DEFECT_LEN_END_9 { get; set; }
		public string DEFECT_CLASS_9 { get; set; }
		public string DEFECT_PERCENT_9 { get; set; }
		public string DEFECT_QUALITY_GRADE_9 { get; set; }
		public string DEFECT_CODE_A { get; set; }
		public string DEFECT_FROM_A { get; set; }
		public string DEFECT_SURF_A { get; set; }
		public string DEFECT_POSITION_WIDTH_A { get; set; }
		public string DEFECT_LEN_START_A { get; set; }
		public string DEFECT_LEN_END_A { get; set; }
		public string DEFECT_CLASS_A { get; set; }
		public string DEFECT_PERCENT_A { get; set; }
		public string DEFECT_QUALITY_GRADE_A { get; set; }
		public string WINDING_DIRE { get; set; }
		public string BETTER_SURF_WARD_CODE { get; set; }
		public string HOLD_MAKER { get; set; }
		public string HOLD_FLAG { get; set; }
		public string HOLD_CAUSE_CODE { get; set; }
		public string SAMPLE_FLAG { get; set; }
		public string TRIM_FLAG { get; set; }
		public string FIXED_WT_FLAG { get; set; }
		public string FINAL_COIL_FLAG { get; set; }
		public string SCRAP_FLAG { get; set; }
		public string SAMPLE_POS_CODE { get; set; }
		public string NO_LEADER_CODE { get; set; }
		public string SURFACE_ACCU_CODE { get; set; }
		public string OFF_ROLL_LEN_HEAD { get; set; }
		public string OFF_ROLL_LEN_TAIL { get; set; }
		public string SURFACE_ACCU_CODE_IN { get; set; }
		public string SURFACE_ACCU_CODE_OUT { get; set; }
		public string FLIP_TAG { get; set; }
		public string PROCESS_CODE { get; set; }
		public string UNCOIL_DIRECTION { get; set; }
		public string RECOILER_ACTTEN_AVG { get; set; }
		public string PAPER_DENSITY { get; set; }
		public string SLEEVE_WEIGHT { get; set; }
	}
}
