using DBService.Base;

namespace DBService.Level25Repository.L2L25_CoilPDI
{
    public class L2L25_CoilPDI : BaseRepositoryModel
    {
		public string Message_Length { get; set; }
		public string Message_Id { get; set; }
		public string Date { get; set; }
		public string Time { get; set; }
		public string PLAN_NO { get; set; }
		public string MAT_PLAN_SEQ_NO { get; set; }
		public string PLAN_TYPE { get; set; }
		public string IN_MAT_NO { get; set; }
		public string IN_MAT_THICK { get; set; }
		public string IN_MAT_WIDTH { get; set; }
		public string IN_MAT_WT { get; set; }
		public string IN_MAT_LEN { get; set; }
		public string IN_MAT_INNER_DIA { get; set; }
		public string IN_MAT_OUTER_DIA { get; set; }
		public string SLEEVE_TYPE_CODE { get; set; }
		public string SLEEVE_DIAMTER { get; set; }
		public string PAPER_REQ_CODE { get; set; }
		public string PAPER_CODE { get; set; }
		public string HEAD_PAPER_LENGTH { get; set; }
		public string HEAD_PAPER_WIDTH { get; set; }
		public string TAIL_PAPER_LENGTH { get; set; }
		public string TAIL_PAPER_WIDTH { get; set; }
		public string TS_MAX { get; set; }
		public string TS_MIN { get; set; }
		public string ST_NO { get; set; }
		public string DENSITY { get; set; }
		public string REPAIR_TYPE { get; set; }
		public string SURFACE_ACCU_CODE { get; set; }
		public string SURFACE_ACCURACY { get; set; }
		public string BETTER_SURF_WARD_CODE { get; set; }
		public string UNCOIL_DIRECTION { get; set; }
		public string OUT_MAT_NO { get; set; }
		public string OUT_PAPER_REQ_CODE { get; set; }
		public string OUT_PAPER_CODE { get; set; }
		public string OUT_SLEEVE_DIAMTER { get; set; }
		public string OUT_SLEEVE_TYPE_CODE { get; set; }
		public string PACK_MODE { get; set; }
		public string LEADER_FLAG { get; set; }
		public string SAMPLE_FLAG { get; set; }
		public string SAMPLE_FRQN_CODE { get; set; }
		public string SAMPLE_LOT_NO { get; set; }
		public string ORIGIN_CODE { get; set; }
		public string PREV_WHOLE_BACKLOG_CODE { get; set; }
		public string NEXT_WHOLE_BACKLOG_CODE { get; set; }
		public string TRIM_FLAG { get; set; }
		public string OUT_MAT_WIDTH { get; set; }
		public string OUT_MAT_MAX_WIDTH { get; set; }
		public string OUT_MAT_MIN_WIDTH { get; set; }
		public string OUT_MAT_THICK { get; set; }
		public string OUT_MAT_INNER_DIA { get; set; }
		public string ORDER_NO { get; set; }
		public string ORDER_UNIT_MAX_WT { get; set; }
		public string ORDER_UNIT_MIN_WT { get; set; }
		public string ORDER_UNIT_AIM_WT { get; set; }
		public string FIXED_WT_FLAG { get; set; }
		public string DIVIDE_NUM { get; set; }
		public string ORDER_WT1 { get; set; }
		public string ORDER_WT2 { get; set; }
		public string ORDER_WT3 { get; set; }
		public string ORDER_WT4 { get; set; }
		public string ORDER_WT5 { get; set; }
		public string ORDER_WT6 { get; set; }
		public string ORDER_NO1 { get; set; }
		public string ORDER_NO2 { get; set; }
		public string ORDER_NO3 { get; set; }
		public string ORDER_NO4 { get; set; }
		public string ORDER_NO5 { get; set; }
		public string ORDER_NO6 { get; set; }
		public string TEST_PLAN_NO { get; set; }
		public string QC_REMARK { get; set; }
		public string HEAD_OFF_GAUGE { get; set; }
		public string TAIL_OFF_GAUGE { get; set; }
		public string SURFACE_ACCU_CODE_IN { get; set; }
		public string SURFACE_ACCU_CODE_OUT { get; set; }
		public string SG_SIGN { get; set; }
		public string PROCESS_CODE { get; set; }
		public string ORDER_CUST_ENAME { get; set; }
		public string ORDER_CUST_CNAME { get; set; }
		public string ORDER_CUST_CODE { get; set; }
		public string SURFACE_ACCU_DESC { get; set; }
		public string SURFACE_ACCURACY_DESC { get; set; }
		public string SURFACE_ACCU_DESC_IN { get; set; }
		public string SURFACE_ACCU_DESC_OUT { get; set; }

		public string DEFECT_CODE1 { get; set; }
		public string DEFECT_FROM1 { get; set; }
		public string DEFECT_SURF1 { get; set; }
		public string DEFECT_POSITION_WIDTH1 { get; set; }
		public string DEFECT_LEN_START1 { get; set; }
		public string DEFECT_LEN_END1 { get; set; }
		public string DEFECT_CLASS1 { get; set; }
		public string DEFECT_PERCENT1 { get; set; }
		public string DEFECT_QUALITY_GRADE1 { get; set; }
		public string DEFECT_CODE2 { get; set; }
		public string DEFECT_FROM2 { get; set; }
		public string DEFECT_SURF2 { get; set; }
		public string DEFECT_POSITION_WIDTH2 { get; set; }
		public string DEFECT_LEN_START2 { get; set; }
		public string DEFECT_LEN_END2 { get; set; }
		public string DEFECT_CLASS2 { get; set; }
		public string DEFECT_PERCENT2 { get; set; }
		public string DEFECT_QUALITY_GRADE2 { get; set; }
		public string DEFECT_CODE3 { get; set; }
		public string DEFECT_FROM3 { get; set; }
		public string DEFECT_SURF3 { get; set; }
		public string DEFECT_POSITION_WIDTH3 { get; set; }
		public string DEFECT_LEN_START3 { get; set; }
		public string DEFECT_LEN_END3 { get; set; }
		public string DEFECT_CLASS3 { get; set; }
		public string DEFECT_PERCENT3 { get; set; }
		public string DEFECT_QUALITY_GRADE3 { get; set; }
		public string DEFECT_CODE4 { get; set; }
		public string DEFECT_FROM4 { get; set; }
		public string DEFECT_SURF4 { get; set; }
		public string DEFECT_POSITION_WIDTH4 { get; set; }
		public string DEFECT_LEN_START4 { get; set; }
		public string DEFECT_LEN_END4 { get; set; }
		public string DEFECT_CLASS4 { get; set; }
		public string DEFECT_PERCENT4 { get; set; }
		public string DEFECT_QUALITY_GRADE4 { get; set; }
		public string DEFECT_CODE5 { get; set; }
		public string DEFECT_FROM5 { get; set; }
		public string DEFECT_SURF5 { get; set; }
		public string DEFECT_POSITION_WIDTH5 { get; set; }
		public string DEFECT_LEN_START5 { get; set; }
		public string DEFECT_LEN_END5 { get; set; }
		public string DEFECT_CLASS5 { get; set; }
		public string DEFECT_PERCENT5 { get; set; }
		public string DEFECT_QUALITY_GRADE5 { get; set; }
		public string DEFECT_CODE6 { get; set; }
		public string DEFECT_FROM6 { get; set; }
		public string DEFECT_SURF6 { get; set; }
		public string DEFECT_POSITION_WIDTH6 { get; set; }
		public string DEFECT_LEN_START6 { get; set; }
		public string DEFECT_LEN_END6 { get; set; }
		public string DEFECT_CLASS6 { get; set; }
		public string DEFECT_PERCENT6 { get; set; }
		public string DEFECT_QUALITY_GRADE6 { get; set; }
		public string DEFECT_CODE7 { get; set; }
		public string DEFECT_FROM7 { get; set; }
		public string DEFECT_SURF7 { get; set; }
		public string DEFECT_POSITION_WIDTH7 { get; set; }
		public string DEFECT_LEN_START7 { get; set; }
		public string DEFECT_LEN_END7 { get; set; }
		public string DEFECT_CLASS7 { get; set; }
		public string DEFECT_PERCENT7 { get; set; }
		public string DEFECT_QUALITY_GRADE7 { get; set; }
		public string DEFECT_CODE8 { get; set; }
		public string DEFECT_FROM8 { get; set; }
		public string DEFECT_SURF8 { get; set; }
		public string DEFECT_POSITION_WIDTH8 { get; set; }
		public string DEFECT_LEN_START8 { get; set; }
		public string DEFECT_LEN_END8 { get; set; }
		public string DEFECT_CLASS8 { get; set; }
		public string DEFECT_PERCENT8 { get; set; }
		public string DEFECT_QUALITY_GRADE8 { get; set; }
		public string DEFECT_CODE9 { get; set; }
		public string DEFECT_FROM9 { get; set; }
		public string DEFECT_SURF9 { get; set; }
		public string DEFECT_POSITION_WIDTH9 { get; set; }
		public string DEFECT_LEN_START9 { get; set; }
		public string DEFECT_LEN_END9 { get; set; }
		public string DEFECT_CLASS9 { get; set; }
		public string DEFECT_PERCENT9 { get; set; }
		public string DEFECT_QUALITY_GRADE9 { get; set; }
		public string DEFECT_CODE10 { get; set; }
		public string DEFECT_FROM10 { get; set; }
		public string DEFECT_SURF10 { get; set; }
		public string DEFECT_POSITION_WIDTH10 { get; set; }
		public string DEFECT_LEN_START10 { get; set; }
		public string DEFECT_LEN_END10 { get; set; }
		public string DEFECT_CLASS10 { get; set; }
		public string DEFECT_PERCENT10 { get; set; }
		public string DEFECT_QUALITY_GRADE10 { get; set; }
		

	}
}
